### ISSUE TITLE
Cloud-init yml config file won't execute during the startup of the instance

### ISSUE THREAD

**Issue by OlegGorj** [OlegGorj/gcp-terraform-ws#20]
## Force to start:

ubuntu@devops-instance-vm2 /var/log $ sudo google_metadata_script_runner --script-type startup

---

## Jornal:

ubuntu@devops-instance-vm2 /var/log $ sudo journalctl -u google-startup-scripts.service
-- Logs begin at Tue 2018-05-15 14:44:31 UTC, end at Tue 2018-05-15 14:47:06 UTC. --
May 15 14:44:36 devops-instance-vm2 systemd[1]: Starting Google Compute Engine Startup Scripts...
May 15 14:44:36 devops-instance-vm2 startup-script[395]: INFO Starting startup scripts.
May 15 14:44:36 devops-instance-vm2 startup-script[395]: INFO Found startup-script in metadata.
May 15 14:44:36 devops-instance-vm2 startup-script[395]: INFO startup-script: /var/lib/google/startup-pgZxHP/tmpdP15eX: line 1: H4sIAAAAAAAA/2xSzW4TMRC+W8o7jMLZ3QVVUIxyAJoDhwCiFAkhhBx7Ekasx9Z4lm4kHh7tbkRD2pNtz
May 15 14:44:36 devops-instance-vm2 startup-script[395]: INFO startup-script: Return code 127.
May 15 14:44:36 devops-instance-vm2 startup-script[395]: INFO Finished running startup scripts.
May 15 14:44:36 devops-instance-vm2 systemd[1]: Started Google Compute Engine Startup Scripts.

**Comment by OlegGorj** [comment]
Changing:
  gzip          = false
  base64_encode = false
in `data "template_cloudinit_config" "ngnix_init"`
produced:

May 15 14:58:33 devops-instance-vm2 systemd[1]: Starting Google Compute Engine Startup Scripts...
May 15 14:58:34 devops-instance-vm2 startup-script[474]: INFO Starting startup scripts.
May 15 14:58:34 devops-instance-vm2 startup-script[474]: INFO Found startup-script in metadata.
May 15 14:58:34 devops-instance-vm2 startup-script[474]: INFO startup-script: /var/lib/google/startup-VzEZQ3/tmpihZhCT: line 1: Content-Type:: command not found
May 15 14:58:34 devops-instance-vm2 startup-script[474]: INFO startup-script: /var/lib/google/startup-VzEZQ3/tmpihZhCT: line 2: MIME-Version:: command not found
May 15 14:58:34 devops-instance-vm2 startup-script[474]: INFO startup-script: /var/lib/google/startup-VzEZQ3/tmpihZhCT: line 3: $'\r': command not found
May 15 14:58:34 devops-instance-vm2 startup-script[474]: INFO startup-script: /var/lib/google/startup-VzEZQ3/tmpihZhCT: line 4: $'--MIMEBOUNDARY\r': command not found
May 15 14:58:34 devops-instance-vm2 startup-script[474]: INFO startup-script: /var/lib/google/startup-VzEZQ3/tmpihZhCT: line 5: Content-Transfer-Encoding:: command not found
May 15 14:58:34 devops-instance-vm2 startup-script[474]: INFO startup-script: /var/lib/google/startup-VzEZQ3/tmpihZhCT: line 6: Content-Type:: command not found
May 15 14:58:34 devops-instance-vm2 startup-script[474]: INFO startup-script: /var/lib/google/startup-VzEZQ3/tmpihZhCT: line 7: Mime-Version:: command not found
May 15 14:58:34 devops-instance-vm2 startup-script[474]: INFO startup-script: /var/lib/google/startup-VzEZQ3/tmpihZhCT: line 8: $'\r': command not found
May 15 14:58:34 devops-instance-vm2 startup-script[474]: INFO startup-script: /var/lib/google/startup-VzEZQ3/tmpihZhCT: line 11: users:: command not found
May 15 14:58:34 devops-instance-vm2 startup-script[474]: INFO startup-script: /var/lib/google/startup-VzEZQ3/tmpihZhCT: line 12: -: command not found
May 15 14:58:34 devops-instance-vm2 startup-script[474]: INFO startup-script: /var/lib/google/startup-VzEZQ3/tmpihZhCT: line 13: uid:: command not found
May 15 14:58:34 devops-instance-vm2 startup-script[474]: INFO startup-script: /var/lib/google/startup-VzEZQ3/tmpihZhCT: line 15: write_files:: command not found
May 15 14:58:34 devops-instance-vm2 startup-script[474]: INFO startup-script: /var/lib/google/startup-VzEZQ3/tmpihZhCT: line 16: -: command not found
May 15 14:58:34 devops-instance-vm2 startup-script[474]: INFO startup-script: /var/lib/google/startup-VzEZQ3/tmpihZhCT: line 17: permissions:: command not found
May 15 14:58:34 devops-instance-vm2 startup-script[474]: INFO startup-script: /var/lib/google/startup-VzEZQ3/tmpihZhCT: line 18: owner:: command not found
May 15 14:58:34 devops-instance-vm2 startup-script[474]: INFO startup-script: /var/lib/google/startup-VzEZQ3/tmpihZhCT: line 20: [Unit]: command not found
May 15 14:58:34 devops-instance-vm2 startup-script[474]: INFO startup-script: /var/lib/google/startup-VzEZQ3/tmpihZhCT: line 19: content:: command not found
May 15 14:58:34 devops-instance-vm2 startup-script[474]: INFO startup-script: /var/lib/google/startup-VzEZQ3/tmpihZhCT: line 21: a: command not found
May 15 14:58:34 devops-instance-vm2 startup-script[474]: INFO startup-script: /var/lib/google/startup-VzEZQ3/tmpihZhCT: line 23: [Service]: command not found
May 15 14:58:34 devops-instance-vm2 startup-script[474]: INFO startup-script: /var/lib/google/startup-VzEZQ3/tmpihZhCT: line 24: run: command not found
May 15 14:58:34 devops-instance-vm2 startup-script[474]: INFO startup-script: /var/lib/google/startup-VzEZQ3/tmpihZhCT: line 25: stop: command not found
May 15 14:58:34 devops-instance-vm2 startup-script[474]: INFO startup-script: rm: cannot remove 'mycloudservice': No such file or directory
May 15 14:58:34 devops-instance-vm2 startup-script[474]: INFO startup-script: /var/lib/google/startup-VzEZQ3/tmpihZhCT: line 28: runcmd:: command not found
May 15 14:58:34 devops-instance-vm2 startup-script[474]: INFO startup-script: /var/lib/google/startup-VzEZQ3/tmpihZhCT: line 29: -: command not found
May 15 14:58:34 devops-instance-vm2 startup-script[474]: INFO startup-script: /var/lib/google/startup-VzEZQ3/tmpihZhCT: line 30: -: command not found
May 15 14:58:34 devops-instance-vm2 startup-script[474]: INFO startup-script: /var/lib/google/startup-VzEZQ3/tmpihZhCT: line 31: $'\r': command not found
May 15 14:58:34 devops-instance-vm2 startup-script[474]: INFO startup-script: /var/lib/google/startup-VzEZQ3/tmpihZhCT: line 32: $'--MIMEBOUNDARY--\r': command not found
May 15 14:58:34 devops-instance-vm2 startup-script[474]: INFO startup-script: Return code 127.
May 15 14:58:34 devops-instance-vm2 startup-script[474]: INFO Finished running startup scripts.

**Comment by Jenishk56** [comment]
@OlegGorj Is there a solution of this?
